### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by Flygsand** [PretendoNetwork/account#21]
I'm interested in implementing password reset. The below is for a browser-based flow. I have no idea how this could be done from a Wii U console. The website part is here: PretendoNetwork/website#101.

I suggest two new endpoints. 

## Start flow
A POST endpoint at `/v1/passwordreset` that accepts a body containing an e-mail address:

```json
{
  "email": "miyamoto@nintendo.co.jp",
  "captcha_response": "..." 
}
```

and if the e-mail is valid and verified, and the captcha checks out, sends an e-mail containing a URL with an access token valid only for the below endpoint for a set time (24 hours?) and one call, and responds `204 No Content`. The URL would have to point to a form, and the host and path could possibly be chosen from a pre-approved set using another JSON field in the above body, or be hardcoded in config.

e.g. `https://pretendo.network/account/password?access_token=eyJhbGciOiJIUzI1NiIsI...` (assuming query parameters aren't logged).

## Update password
A PUT endpoint at `/v1/password` for updating passwords with a `204 No Content` response code on success.

```json
{
  "password": "thisisverysecret",
  "password_confirm": "thisisverysecret"
}
```

I threw this together pretty quickly so there's probably a lot to be desired. I'd be happy to receive any input, suggestions, ideas, etc. that you might have.

**Comment by InternalLoss** [comment]
Endpoints should already exist for a password reset on NNID - let me get back to you, I'll have captures of this (though the method you described may make more sense from the web itself, I'd like to support password resets working on-device)

**Comment by InternalLoss** [comment]
LUCKILY this is expected to be done from-web; console will send `GET https://account.nintendo.net/v1/api/support/forgotten_password/{PID}` and will send an email. Example from Nintendo:
```
This email has been automatically sent from Nintendo following your request for a temporary password for your Nintendo Network ID.

A temporary password has been issued to allow you to keep using your Nintendo Network ID.

The temporary password is: {TEMP PASSWORD}

This temporary password will expire 24 hours from the time this email was sent. If the 24-hour period has expired, please repeat the procedure to have a new temporary password issued.

If it is used within 24 hours, you can continue to use it as your password. However, due to security concerns with regard to your ID, we recommend changing the password.
To change the password on Wii U, touch the Mii on the top left of the Wii U Menu to access User Settings, then touch the Change Password option under Nintendo Network ID Settings. 
To change the password on a system in the Nintendo 3DS family, access Nintendo Network ID Settings in System Settings.

Thank you for using Nintendo Network.

--------------------
NOTE: Please do not reply to this email address.

Please contact us by email for any enquiries. Local contact details for Nintendo Customer Support can be found at: contact.nintendo.eu

Nintendo of Europe GmbH, Herriotstr. 4, 60528 Frankfurt am Main, Germany
VAT number: DE132095955. Registered at: Amtsgericht Frankfurt am Main HRB 101840. Geschäftsführer (Managing Director): Koji Miyake

This email has been sent to you in English as your Nintendo Network ID is linked to a console with English set as its system language.
```

We can, of course, just send a token-based email and don't reset unless the email has been used (**remember, we must have the same constraints that Nintendo does on passwords** which is A-Z, a-z, 0-9, and the characters `~$%^&*()_"+|<>;:#-=/,.?!@`\{}[]`

**Comment by jonbarrow** [comment]
Password resetting has been implemented on both consoles and the website now

**Comment by Flygsand** [comment]
Nice work! Has this gone live? Password reset on device doesn't work for me and the website password reset link is broken.

**Comment by jonbarrow** [comment]
It has not gone live yet, as the associated [website PR](https://github.com/PretendoNetwork/website/pull/177) has not been reviewed and merged yet
