### ISSUE TITLE
Implement marketing/access flag

### ISSUE THREAD

**Issue by InternalLoss** [PretendoNetwork/account#25]
If a user has restricted access to their NNID, Nintendo will not allow login on web (and we should do the same)! This is done by PUT `https://account.nintendo.net/v1/api/people/@me/`: 

```xml
<person>
	<off_device_flag>Y</off_device_flag>
</person>
```

Y = allow login off-device
N = no login allowed off-device (this includes app, web, etc)

Marketing is the same:
```xml
<person>
	<marketing_flag>Y</marketing_flag>
</person>
```

but Y = yes, opt-in
and N = no, opt-out

We should use this to add/remove users to our newsletter [if we have one?]

**Comment by jonbarrow** [comment]
> We should use this to add/remove users to our newsletter [if we have one?]

We don't have one at the moment. What did Nintendo's newsletter contain? Should we even have one?

**Comment by InternalLoss** [comment]
> > We should use this to add/remove users to our newsletter [if we have one?]
> 
> We don't have one at the moment. What did Nintendo's newsletter contain? Should we even have one?

Nintendo didn't really have a newsletter, but general marketing ("Hey, new game!") etc was sent out with this enabled - if you were under 16 it was enforced that this was disabled, so I've never seen it.

Maybe we should use it when we're in full swing for "hey guys new game support!"?

**Comment by jonbarrow** [comment]
>  We should 100% store the flag and even if we don't use it for a year or two

I do store it already, just don't update it anywhere https://github.com/PretendoNetwork/account/blob/master/src/models/pnid.js#L77-L81

**Comment by InternalLoss** [comment]
I meant store it and update ^^
