### ISSUE TITLE
Idea: Local saving files option

### ISSUE THREAD

**Issue by ghost** [PretendoNetwork/account#39]
I have a idea but i don't know if that's useful but can we have like a local storage that we can just storage the files in a folder on our computers?
For testing and self hosting would be useful because not many people can get a AWS or want to.

**Comment by jonbarrow** [comment]
You do not need to use AWS, just na S3 compatible server. There are several S3 compatible servers availavle such as [Spaces from DigitalOcean](https://www.digitalocean.com/products/spaces) and [B2 from BackBlaze](https://www.backblaze.com/b2/cloud-storage.html)

There are also several self-hosted solutions such as [MinIO](https://min.io/product/s3-compatibility) and [Zenko](https://www.zenko.io/cloudserver/)

The account server is not meant to be used as a CDN so I will likely not be supporting local file storage

**Comment by jonbarrow** [comment]
This has been implemented as of https://github.com/PretendoNetwork/account/commit/8ab51d7f96496ef585c7d4a81c856e5fc52f01a5
