### ISSUE TITLE
`/v1/api/miis` does not behave the same as the endpoint on the official servers

### ISSUE THREAD

**Issue by superwhiskers** [PretendoNetwork/account#58]
- [x] the response returned if no miis are associated with the pids requested should have an empty body and a status code of `404`
- [x] the endpoint should properly handle multiple comma-delimited pids provided in the `pids` url parameter, instead of hanging
- [x] if at least one pid has an associated mii, the mii data should be returned for those pids and any information about pids without an associated mii should be omitted. the status code should be `200`

**Comment by jonbarrow** [comment]
Only 1 of these, the first one, was actually not working correctly. This has been fixed as of https://github.com/PretendoNetwork/account/commit/e42329cb735adad41ddfa09a0d1d8f1cd67e850a. Thank you for the report, if you find any other inconsistencies let us know
