### ISSUE TITLE
Not really an issue, but more of a question

### ISSUE THREAD

**Issue by JesseFST** [PretendoNetwork/account#6]
How can you create a user account, without access to a real Wii U?  
Basically, I want to create a NNID (or in this case, a PNID?) and login to it through Cemu.

**Comment by superwhiskers** [comment]
iirc that's going to be implemented into the website

**Comment by AsrielNeko** [comment]
you can fix this?
> ursa@0.9.4 install C:\account-master\node_modules\ursa
> node-gyp rebuild


C:\account-master\node_modules\ursa>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\account-master\node_modules\ursa
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN account.nintendo.net@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ursa@0.9.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ursa@0.9.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DigbyKun\AppData\Roaming\npm-cache\_logs\2019-04-14T05_22_52_190Z-debug.log

**Comment by superwhiskers** [comment]
you don't have a python install @AsrielNeko, so you need to install it. you can find an installer [here](https://python.org)

**Comment by AsrielNeko** [comment]
Okay i try it thanks @superwhiskers

**Comment by superwhiskers** [comment]
np

**Comment by AsrielNeko** [comment]
After I Install Python

> ursa@0.9.4 install C:\account-master\node_modules\ursa
> node-gyp rebuild


C:\account-master\node_modules\ursa>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\DigbyKun\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\account-master\node_modules\ursa
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN account.nintendo.net@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ursa@0.9.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ursa@0.9.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DigbyKun\AppData\Roaming\npm-cache\_logs\2019-04-16T10_27_31_307Z-debug.log

[2019-04-16T10_27_31_307Z-debug.log](https://github.com/PretendoNetwork/account/files/3084414/2019-04-16T10_27_31_307Z-debug.log)

now what @superwhiskers ?

**Comment by superwhiskers** [comment]
node-gyp only supports python2.x, you probably installed python3.x :p so you need to go to the python website and install the latest version in the 2.x series

**Comment by AsrielNeko** [comment]
Haaaaa ok i will try

**Comment by AsrielNeko** [comment]
**error again**
C:\account-master>npm i node-gyp

> ursa@0.9.4 install C:\account-master\node_modules\ursa
> node-gyp rebuild


C:\account-master\node_modules\ursa>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  ursaNative.cc
  win_delay_load_hook.cc
c:\account-master\node_modules\ursa\src\ursanative.cc(389): error C2027: use of undefined type 'rsa_st' [C:\account-mas
ter\node_modules\ursa\build\ursaNative.vcxproj]
  c:\users\digbykun\.node-gyp\10.15.3\include\node\openssl\evp.h(914): note: see declaration of 'rsa_st'
c:\account-master\node_modules\ursa\src\ursanative.cc(390): error C2027: use of undefined type 'rsa_st' [C:\account-mas
ter\node_modules\ursa\build\ursaNative.vcxproj]
  c:\users\digbykun\.node-gyp\10.15.3\include\node\openssl\evp.h(914): note: see declaration of 'rsa_st'
c:\account-master\node_modules\ursa\src\ursanative.cc(407): error C2027: use of undefined type 'rsa_st' [C:\account-mas
ter\node_modules\ursa\build\ursaNative.vcxproj]
  c:\users\digbykun\.node-gyp\10.15.3\include\node\openssl\evp.h(914): note: see declaration of 'rsa_st'
c:\account-master\node_modules\ursa\src\ursanative.cc(488): warning C4996: 'v8::Value::Uint32Value': was declared depre
cated [C:\account-master\node_modules\ursa\build\ursaNative.vcxproj]
  c:\users\digbykun\.node-gyp\10.15.3\include\node\v8.h(2477): note: see declaration of 'v8::Value::Uint32Value'
c:\account-master\node_modules\ursa\src\ursanative.cc(489): warning C4996: 'v8::Value::Uint32Value': was declared depre
cated [C:\account-master\node_modules\ursa\build\ursaNative.vcxproj]
  c:\users\digbykun\.node-gyp\10.15.3\include\node\v8.h(2477): note: see declaration of 'v8::Value::Uint32Value'
c:\account-master\node_modules\ursa\src\ursanative.cc(536): error C2027: use of undefined type 'rsa_st' [C:\account-mas
ter\node_modules\ursa\build\ursaNative.vcxproj]
  c:\users\digbykun\.node-gyp\10.15.3\include\node\openssl\evp.h(914): note: see declaration of 'rsa_st'
c:\account-master\node_modules\ursa\src\ursanative.cc(536): error C2660: 'bignumToBuffer': function does not take 1 arg
uments [C:\account-master\node_modules\ursa\build\ursaNative.vcxproj]
  c:\account-master\node_modules\ursa\src\ursanative.cc(100): note: see declaration of 'bignumToBuffer'
c:\account-master\node_modules\ursa\src\ursanative.cc(552): error C2027: use of undefined type 'rsa_st' [C:\account-mas
ter\node_modules\ursa\build\ursaNative.vcxproj]
  c:\users\digbykun\.node-gyp\10.15.3\include\node\openssl\evp.h(914): note: see declaration of 'rsa_st'
c:\account-master\node_modules\ursa\src\ursanative.cc(552): error C2660: 'bignumToBuffer': function does not take 1 arg
uments [C:\account-master\node_modules\ursa\build\ursaNative.vcxproj]
  c:\account-master\node_modules\ursa\src\ursanative.cc(100): note: see declaration of 'bignumToBuffer'
c:\account-master\node_modules\ursa\src\ursanative.cc(567): error C2027: use of undefined type 'rsa_st' [C:\account-mas
ter\node_modules\ursa\build\ursaNative.vcxproj]
  c:\users\digbykun\.node-gyp\10.15.3\include\node\openssl\evp.h(914): note: see declaration of 'rsa_st'
c:\account-master\node_modules\ursa\src\ursanative.cc(567): error C2660: 'bignumToBuffer': function does not take 1 arg
uments [C:\account-master\node_modules\ursa\build\ursaNative.vcxproj]
  c:\account-master\node_modules\ursa\src\ursanative.cc(100): note: see declaration of 'bignumToBuffer'
c:\account-master\node_modules\ursa\src\ursanative.cc(683): warning C4996: 'v8::Value::Uint32Value': was declared depre
cated [C:\account-master\node_modules\ursa\build\ursaNative.vcxproj]
  c:\users\digbykun\.node-gyp\10.15.3\include\node\v8.h(2477): note: see declaration of 'v8::Value::Uint32Value'
c:\account-master\node_modules\ursa\src\ursanative.cc(730): warning C4996: 'v8::Value::Uint32Value': was declared depre
cated [C:\account-master\node_modules\ursa\build\ursaNative.vcxproj]
  c:\users\digbykun\.node-gyp\10.15.3\include\node\v8.h(2477): note: see declaration of 'v8::Value::Uint32Value'
c:\account-master\node_modules\ursa\src\ursanative.cc(776): warning C4996: 'v8::Value::Uint32Value': was declared depre
cated [C:\account-master\node_modules\ursa\build\ursaNative.vcxproj]
  c:\users\digbykun\.node-gyp\10.15.3\include\node\v8.h(2477): note: see declaration of 'v8::Value::Uint32Value'
c:\account-master\node_modules\ursa\src\ursanative.cc(822): warning C4996: 'v8::Value::Uint32Value': was declared depre
cated [C:\account-master\node_modules\ursa\build\ursaNative.vcxproj]
  c:\users\digbykun\.node-gyp\10.15.3\include\node\v8.h(2477): note: see declaration of 'v8::Value::Uint32Value'
c:\account-master\node_modules\ursa\src\ursanative.cc(928): warning C4996: 'v8::Value::Uint32Value': was declared depre
cated [C:\account-master\node_modules\ursa\build\ursaNative.vcxproj]
  c:\users\digbykun\.node-gyp\10.15.3\include\node\v8.h(2477): note: see declaration of 'v8::Value::Uint32Value'
c:\account-master\node_modules\ursa\src\ursanative.cc(982): warning C4996: 'v8::Value::Uint32Value': was declared depre
cated [C:\account-master\node_modules\ursa\build\ursaNative.vcxproj]
  c:\users\digbykun\.node-gyp\10.15.3\include\node\v8.h(2477): note: see declaration of 'v8::Value::Uint32Value'
c:\account-master\node_modules\ursa\src\ursanative.cc(1044): warning C4996: 'v8::Value::Uint32Value': was declared depr
ecated [C:\account-master\node_modules\ursa\build\ursaNative.vcxproj]
  c:\users\digbykun\.node-gyp\10.15.3\include\node\v8.h(2477): note: see declaration of 'v8::Value::Uint32Value'
c:\account-master\node_modules\ursa\src\ursanative.cc(1065): warning C4996: 'v8::Value::Uint32Value': was declared depr
ecated [C:\account-master\node_modules\ursa\build\ursaNative.vcxproj]
  c:\users\digbykun\.node-gyp\10.15.3\include\node\v8.h(2477): note: see declaration of 'v8::Value::Uint32Value'
c:\account-master\node_modules\ursa\src\ursanative.cc(1102): warning C4996: 'v8::Value::Uint32Value': was declared depr
ecated [C:\account-master\node_modules\ursa\build\ursaNative.vcxproj]
  c:\users\digbykun\.node-gyp\10.15.3\include\node\v8.h(2477): note: see declaration of 'v8::Value::Uint32Value'
c:\account-master\node_modules\ursa\src\ursanative.cc(1135): warning C4996: 'v8::Value::Uint32Value': was declared depr
ecated [C:\account-master\node_modules\ursa\build\ursaNative.vcxproj]
  c:\users\digbykun\.node-gyp\10.15.3\include\node\v8.h(2477): note: see declaration of 'v8::Value::Uint32Value'
c:\account-master\node_modules\ursa\src\ursanative.cc(1218): error C2027: use of undefined type 'rsa_st' [C:\account-ma
ster\node_modules\ursa\build\ursaNative.vcxproj]
  c:\users\digbykun\.node-gyp\10.15.3\include\node\openssl\evp.h(914): note: see declaration of 'rsa_st'
c:\account-master\node_modules\ursa\src\ursanative.cc(1219): error C2027: use of undefined type 'rsa_st' [C:\account-ma
ster\node_modules\ursa\build\ursaNative.vcxproj]
  c:\users\digbykun\.node-gyp\10.15.3\include\node\openssl\evp.h(914): note: see declaration of 'rsa_st'
c:\account-master\node_modules\ursa\src\ursanative.cc(1220): error C2027: use of undefined type 'rsa_st' [C:\account-ma
ster\node_modules\ursa\build\ursaNative.vcxproj]
  c:\users\digbykun\.node-gyp\10.15.3\include\node\openssl\evp.h(914): note: see declaration of 'rsa_st'
c:\account-master\node_modules\ursa\src\ursanative.cc(1221): error C2027: use of undefined type 'rsa_st' [C:\account-ma
ster\node_modules\ursa\build\ursaNative.vcxproj]
  c:\users\digbykun\.node-gyp\10.15.3\include\node\openssl\evp.h(914): note: see declaration of 'rsa_st'
c:\account-master\node_modules\ursa\src\ursanative.cc(1222): error C2027: use of undefined type 'rsa_st' [C:\account-ma
ster\node_modules\ursa\build\ursaNative.vcxproj]
  c:\users\digbykun\.node-gyp\10.15.3\include\node\openssl\evp.h(914): note: see declaration of 'rsa_st'
c:\account-master\node_modules\ursa\src\ursanative.cc(1223): error C2027: use of undefined type 'rsa_st' [C:\account-ma
ster\node_modules\ursa\build\ursaNative.vcxproj]
  c:\users\digbykun\.node-gyp\10.15.3\include\node\openssl\evp.h(914): note: see declaration of 'rsa_st'
c:\account-master\node_modules\ursa\src\ursanative.cc(1224): error C2027: use of undefined type 'rsa_st' [C:\account-ma
ster\node_modules\ursa\build\ursaNative.vcxproj]
  c:\users\digbykun\.node-gyp\10.15.3\include\node\openssl\evp.h(914): note: see declaration of 'rsa_st'
c:\account-master\node_modules\ursa\src\ursanative.cc(1225): error C2027: use of undefined type 'rsa_st' [C:\account-ma
ster\node_modules\ursa\build\ursaNative.vcxproj]
  c:\users\digbykun\.node-gyp\10.15.3\include\node\openssl\evp.h(914): note: see declaration of 'rsa_st'
c:\account-master\node_modules\ursa\src\ursanative.cc(1270): error C2027: use of undefined type 'rsa_st' [C:\account-ma
ster\node_modules\ursa\build\ursaNative.vcxproj]
  c:\users\digbykun\.node-gyp\10.15.3\include\node\openssl\evp.h(914): note: see declaration of 'rsa_st'
c:\account-master\node_modules\ursa\src\ursanative.cc(1271): error C2027: use of undefined type 'rsa_st' [C:\account-ma
ster\node_modules\ursa\build\ursaNative.vcxproj]
  c:\users\digbykun\.node-gyp\10.15.3\include\node\openssl\evp.h(914): note: see declaration of 'rsa_st'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\account-master\node_modules\ursa
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN account.nintendo.net@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ursa@0.9.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ursa@0.9.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DigbyKun\AppData\Roaming\npm-cache\_logs\
[2019-04-17T05_50_30_971Z-debug.log](https://github.com/PretendoNetwork/account/files/3088089/2019-04-17T05_50_30_971Z-debug.log)
2019-04-17T05_42_41_673Z-debug.log

**Comment by RedDuckss** [comment]
Closing this issue as the original issue was answered. PNIDs are created on the website, see https://github.com/PretendoNetwork/website/tree/dev
