### ISSUE TITLE
server won't run

### ISSUE THREAD

**Issue by freezermonkey2** [PretendoNetwork/account#89]
![Screenshot 2024-03-31 052030](https://github.com/PretendoNetwork/account/assets/90546506/ed4640fe-08d8-4d21-b22f-5a9eb4e70109)
the server well just give me this error when i try to run it

**Comment by LunarN0v4** [comment]
Are you running a MongoDB server and have you set it up properly?  
This error is about not being able to connect to a MongoDB server.

**Comment by jonbarrow** [comment]
You aren't running a Mongo server that can be connected to. Setting up the Mongo server is out of the scope of support for this repository, as it is not an issue with the server itself. Switch to the `dev` branch and read the setup guide. Closing
